/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "node_node_constants.h"

namespace csci_5105 { namespace PA1 {

const node_nodeConstants g_node_node_constants;

node_nodeConstants::node_nodeConstants() {
}

}} // namespace

