/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef node_client_CONSTANTS_H
#define node_client_CONSTANTS_H

#include "node_client_types.h"

namespace csci_5105 { namespace PA1 {

class node_clientConstants {
 public:
  node_clientConstants();

};

extern const node_clientConstants g_node_client_constants;

}} // namespace

#endif
