/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef node_CONSTANTS_H
#define node_CONSTANTS_H

#include "node_types.h"

namespace csci_5105 { namespace PA1 {

class nodeConstants {
 public:
  nodeConstants();

};

extern const nodeConstants g_node_constants;

}} // namespace

#endif
