/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "node_client_constants.h"

namespace csci_5105 { namespace PA1 {

const node_clientConstants g_node_client_constants;

node_clientConstants::node_clientConstants() {
}

}} // namespace

