/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "superNode_constants.h"

namespace csci_5105 { namespace PA1 {

const superNodeConstants g_superNode_constants;

superNodeConstants::superNodeConstants() {
}

}} // namespace

