/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef superNode_CONSTANTS_H
#define superNode_CONSTANTS_H

#include "superNode_types.h"

namespace csci_5105 { namespace PA1 {

class superNodeConstants {
 public:
  superNodeConstants();

};

extern const superNodeConstants g_superNode_constants;

}} // namespace

#endif
