/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef superNode_TYPES_H
#define superNode_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>
#include "shared_types.h"


namespace csci_5105 { namespace PA1 {

struct State {
  enum type {
    INIT = 1,
    ADDING = 2,
    WORKING = 3,
    BUSY = 4
  };
};

extern const std::map<int, const char*> _State_VALUES_TO_NAMES;

}} // namespace

#endif
